const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const dotenv = require('dotenv');
dotenv.config();
const app = express();
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_URL || '*', methods: ['GET','POST','PUT','DELETE'], allowedHeaders: ['Content-Type','Authorization'] }));
app.use(express.json({ limit: '10mb' }));
app.use('/api', rateLimit({ windowMs: 15*60*1000, max: 200, message: { msg: 'too many requests' } }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/suno', require('./routes/suno'));
app.use('/api/cover', require('./routes/cover'));
app.use('/api/transcribe', require('./routes/transcribe'));
app.use('/api/payment', require('./routes/payment'));
app.use('/api/payment-settings', require('./routes/paymentSettings'));
app.use('/api/admin', require('./routes/admin'));
app.get('/api/health', (req, res) => res.json({ status: 'OK', time: new Date().toISOString() }));
app.use((req, res) => res.status(404).json({ msg: 'Route not found' }));
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ msg: 'Server error' }); });
const PORT = process.env.PORT || 5000;
['MONGO_URI','JWT_SECRET'].forEach(k => { if (!process.env[k]) { console.error('Missing '+k); process.exit(1); } });
mongoose.connect(process.env.MONGO_URI).then(() => { console.log('MongoDB connected!'); app.listen(PORT, () => console.log('Server on port '+PORT)); }).catch(err => { console.error('DB:', err.message); process.exit(1); });
